### ISSUE TITLE
Dependency warning for @babel/core version

### ISSUE THREAD

**Issue by Roralee** [Pilatch/easy-element#14]
When doing an install, I'm getting this warning which is keeping me from being able to run my component.

`warning "easy-element > @babel/plugin-transform-classes@7.0.0-beta.35" has incorrect peer dependency "@babel/core@7.0.0-beta.35".`

**Comment by Pilatch** [comment]
OK. I'll check it out.

**Comment by Pilatch** [comment]
Published 1.4.1 https://github.com/Pilatch/easy-element/releases/tag/1.4.1

Give that a try and let me know how it goes.
